app_name: "HudiIncrementalPipeline"
hudi_version: "1.0.2"
scala_version: "2.12"

spark_config:
  spark.sql.session.timeZone: "UTC"
  spark.sql.extensions: "org.apache.spark.sql.hudi.HoodieSparkSessionExtension"
  spark.sql.catalog.spark_catalog: "org.apache.spark.sql.hudi.catalog.HoodieCatalog"
  spark.serializer: "org.apache.spark.serializer.KryoSerializer"
  spark.default.parallelism: "100"
  spark.sql.shuffle.partitions: "100"
  spark.executor.memory: "4g"
  spark.driver.memory: "2g"
  spark.executor.instances: "4"
  spark.executor.cores: "2"
  spark.task.cpus: "1"
  spark.sql.hive.convertMetastoreParquet: "false"